// 📁 C:\Users\Ayaan1\AndroidStudioProjects\UltimateAccessApp\settings.gradle

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "UltimateAccessApp"
include ':app'